name: Run Tests

on:
  pull_request:
    branches:
      - lib
      - library/next
      - library/beta
      - library/dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 9.6.0
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Lint library
        run: pnpm lint
      - name: Test library
        run: pnpm test