name: Release

on:
  push:
    branches:
      - lib
      - library/next
      - library/beta
      - library/develop

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm ci
      - name: Lint library
        run: npm run lint
      - name: Build library
        run: npm run build:lib
      - name: Test library
        run: npm run test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "Egoka"
          GIT_AUTHOR_EMAIL: "eg.bonda2014@gmail.com"
          GIT_COMMITTER_NAME: "Egoka"
          GIT_COMMITTER_EMAIL: "eg.bonda2014@gmail.com"
        run: npx semantic-release
