name: Release

on:
  push:
    branches:
      - lib
      - library/next
      - library/beta
      - library/develop

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - uses: pnpm/action-setup@v2
        with:
          version: 9.6.0
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Lint library
        run: pnpm lint
      - name: Build library
        run: pnpm build:lib
      - name: Test library
        run: pnpm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: npx semantic-release