name: Release

on:
  push:
    branches:
      - lib
      - library/next
      - library/beta
      - library/develop

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 9.6.0
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Lint library
        run: pnpm lint
      - name: Build library
        run: pnpm build:lib
      - name: Test library
        run: pnpm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "Egoka"
          GIT_AUTHOR_EMAIL: "eg.bonda2014@gmail.com"
          GIT_COMMITTER_NAME: "Egoka"
          GIT_COMMITTER_EMAIL: "eg.bonda2014@gmail.com"
        run: npx semantic-release
      - name: Read version from package.json
        id: read_version
        run: |
          VERSION=$(jq -r '.version' lib/package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Print version
        run: echo "The current version is ${{ env.VERSION }}"
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GIT_AUTHOR_NAME: "Egoka"
          GIT_AUTHOR_EMAIL: "eg.bonda2014@gmail.com"
          GIT_COMMITTER_NAME: "Egoka"
          GIT_COMMITTER_EMAIL: "eg.bonda2014@gmail.com"
        run: |
          git add .A
          git commit -m "release(${{ env.VERSION }}): [skip ci]"
          git push origin ${{ env.BRANCH_NAME }}