name: Release

on:
  push:
    branches:
      - lib
      - library/next
      - library/beta
      - library/develop

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 9.6.0
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Lint library
        run: pnpm lint
      - name: Build library
        run: pnpm build:lib
      - name: Test library
        run: pnpm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "Egoka"
          GIT_AUTHOR_EMAIL: "eg.bonda2014@gmail.com"
          GIT_COMMITTER_NAME: "Egoka"
          GIT_COMMITTER_EMAIL: "eg.bonda2014@gmail.com"
        run: npx semantic-release
      - name: Get release version
        if: steps.release.outputs.new_release_published == 'true'
        run:
          echo "Release version: ${{ steps.release.outputs.new_release_version }}"
