name: Update Changelog

on:
  push:
    branches:
      - test

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - run: pnpm install --frozen-lockfile
      - name: Build library
        run: pnpm build:lib
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "Egoka"
          GIT_AUTHOR_EMAIL: "eg.bonda2014@gmail.com"
          GIT_COMMITTER_NAME: "Egoka"
          GIT_COMMITTER_EMAIL: "eg.bonda2014@gmail.com"
        run: npx semantic-release
      - name: Add date to CHANGELOG
        run: |
          echo "$(date)" >> CHANGELOG.md
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GIT_AUTHOR_NAME: "Egoka"
          GIT_AUTHOR_EMAIL: "eg.bonda2014@gmail.com"
          GIT_COMMITTER_NAME: "Egoka"
          GIT_COMMITTER_EMAIL: "eg.bonda2014@gmail.com"
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG [skip ci]"
          git push origin test